version: "3.7"

services:
  # postgres
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always

volumes:
  db_data:
